FROM nvcr.io/nvidia/l4t-base:r32.3.1
#FROM golang:1.12

# Install go

ENV GOLANG_VERSION 1.12.10
RUN wget -nv -O - https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-arm64.tar.gz \
    | tar -C /usr/local -xz
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends make git

RUN mkdir /k8s-device-plugin
WORKDIR /k8s-device-plugin

# Using go mod download to speed up Golang Docker builds
# https://medium.com/@petomalina/using-go-mod-download-to-speed-up-golang-docker-builds-707591336888?fbclid=IwAR0Jzs5PqepVJTHsshx5sKDftoCbM3IdlW-RD8_hcH6Nlets3lm3Y0LiX3U

# COPY go.mod and go.sum files to the workspace
COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
#RUN go mod download

COPY . .
RUN if [ ! -d "/k8s-device-plugin/vendor" ]; then  go mod vendor; fi
#RUN go mod vendor
RUN make build-in-docker-cuda



FROM debian:stretch-slim

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=utility

COPY --from=0 /k8s-device-plugin/bin/k8s-device-plugin /usr/bin/nvidia-device-plugin

CMD ["nvidia-device-plugin"]



